<?php 
$this->headScript()
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/excanvas.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.resize.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.time.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.pie.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.canvas.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.categories.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.crosshair.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.errorbars.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.fillbetween.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.navigate.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.image.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.stack.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.symbol.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.3/jquery.flot.threshold.min.js')
?>
<script type="text/javascript">
	$(function() {
		
		var data = [
			<?php 
			foreach ($this->issuanceratio as $issuance) {
			    echo "{ label: \"$issuance[STATUS]\", data: $issuance[COUNT] },";
			}
			?>
// 			{ label: "Returned", data: 95 },
// 			{ label: "Outstanding", data: 5 },
			];
		$.plot("#issuanceratio", data, {
			series: {
    			pie: {
    				show: true,
    			}
			},
			legend: {
				show: false,
			},
			grid: {
				hoverable: true,
				clickable: true
			}
		});

		var data = [
			<?php 
			foreach ($this->partyratio as $party) {
			    echo "{ label: \"$party[NAME]\", data: 50 },";
			}
			?>
// 			{ label: "Democrats", data: .45, color: "Blue" },
// 			{ label: "Republicans", data: .5565, color: "Red" },
			];
		$.plot("#partyratio", data, {
			series: {
    			pie: {
    				show: true,
    			}
			},
			legend: {
				show: false,
			},
			grid: {
				hoverable: true,
				clickable: true
			}
		});

		$("#footer").append(" &ndash; Flot " + $.plot.version);
	});
</script>
<div class="jumbotron">
    <h1>Welcome to the <span class="zf-green"><?= \Application\Module::TITLE ?></span> Application</h1>

    <p>
        Congratulations! You have successfully installed the <?= \Application\Module::TITLE ?>.
        You are currently running <?= \Application\Module::TITLE ?> version <?= \Application\Module::VERSION ?>.
        
    </p>

</div>

<div class="card-deck">

	<div class="card mb-4">
		<div class="card-header">
			<h4>Issuance Ratio</h4>
		</div>
		<div class="card-body">
			<div id="issuanceratio" style="padding: 0px; height: 320px;"></div>
		</div>
	</div>
	
	<div class="card mb-4">
		<div class="card-header">
			<h4>Party Ratio</h4>
		</div>
		<div class="card-body">
			<div id="partyratio" style="padding: 0px; height: 320px;"></div>
		</div>
	</div>

</div>